#Drag and drop the Folders generated by DAIN to extract the Gifs from them
#Change the "for file in *limitPallete*.gif;" to change which files you want to extract
#Change the "cd output_videos" go look in other folders
#Change the "cp $file ../../"$FILENAME"_dain.gif" line to change the output filename
echo $@
for FOLDER in "$@";
do
    FOLDER2=$(cygpath "$FOLDER" -u -a)
    #echo Cygpath folder is $FOLDER2
    FILENAME=$(basename -- "$FOLDER2")
    echo $FOLDER2
    cd "$FOLDER2"
    cd output_videos
    for file in *limitPallete*.gif;
    do
        OUTPUTNAME= "$FILENAME"_dain.gif
        echo $OUTPUTNAME
        cp $file ../../"$OUTPUTNAME"
    done
done
echo Done
exec $SHELL